version: "3.9"
services:
  postgres:
    container_name: postgres_jee
    image: "postgres:15"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qsdqsd
      POSTGRES_DB: insta_db_lite
    ports:
      - "5432:5432"

