version: "3.9"
services:
  postgres:
    container_name: postgres_jee
    image: "postgres:15"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: insta_lite_db
    networks:
      - local
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_jee
    image: "dpage/pgadmin4:5.1"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@domain.local
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    networks:
      - local
networks:
  local:
    driver: bridge
volumes:
  postgres_data:



