version: "3.9"
services:
  backend-db:
    container_name: backend-db
    image: "postgres:15"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - backend_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: instaliteadmin
      POSTGRES_PASSWORD: instAl1t€.!
      POSTGRES_DB: insta_lite_db
    networks:
      - instalite
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    depends_on:
      - backend-db
    build:
      context: ./back/.
    volumes:
      - ./data:/app/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://backend-db/insta_lite_db
      - SPRING_DATASOURCE_USERNAME=instaliteadmin
      - SPRING_DATASOURCE_PASSWORD=instAl1t€.!
      - RESOURCE_PATH=/app/data
    networks:
      - instalite
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ./front/.
    environment:
      - REACT_APP_INSTALITE_API_BASE_URL="http://backend:8080"
    networks:
      - instalite
    ports:
      - "5173:5173"

networks:
  instalite:
    driver: bridge

volumes:
  backend_db_data: